version: "3.7"
services:
  tourserver:
    build:
      context: ./tours-service/tours-service/
      dockerfile: Dockerfile
    image: aplikacijadocker
    container_name: aplikacijakon
    restart: always
    networks:
      - tourserver
    ports:
      - 8083:8083
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: postgreskon
    restart: always
    networks:
      - tourserver
    ports:
      - 4000:5432
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: nzm
    volumes:
      - database-data:/var/lib/postgresql/data

  encounterserver:
    build:
      context: ./encounters-service/encounters-service/
      dockerfile: Dockerfile
    image: aplikacijaenkdok
    container_name: aplikacijaenkkon
    restart: always
    networks:
      - encounterserver
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - MONGO_DB_URI=mongodb://root:pass@mongo:27017
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    networks:
      - encounterserver
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    # Docker healtcheck - checks if database is "alive"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - encounterserver
    environment:
      # hostname of mongo databse
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - mongo_express_data:/data/db
  
  followerserver:
    build:
      context: ./follower-microservice/follower-microservice/
      dockerfile: Dockerfile
    image: followerdocker
    container_name: aplikacijafollower
    restart: always
    networks:
      - followerserver
    ports:
      - 8089:8089
    environment:
      - PORT=8089
      - NEO4J_DB=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=Dejann03
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    image: neo4j
    container_name: neo4jfollower
    restart: always
    networks:
      - followerserver
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
         # Docker healtcheck - checks if database is "alive"
    healthcheck:
      # test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a <NEO4J_dbms_connector_bolt_listen__address> -u <user defined username> -p <user defined password> || exit 1" ]
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p Dejann03 || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10 
    environment:
      - NEO4J_AUTH=neo4j/Dejann03
    volumes:
      - databasef-data:/data

  explorerv:
    build:
      dockerfile: Dockerfile
      context: ./psw-back-end/
      target: final
    restart: on-failure
    networks:
      - databasepsw
    ports:
      - "44333:80"
    environment:
      DATABASE_HOST: databasepsw
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorerv
    depends_on:
      - databasepsw

  databasepsw:
    image: postgres:13
    restart: always
    networks:
      - databasepsw
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: explorerv
    ports:
      - "5432:5432"
    volumes:       
      - type: volume
        source: databasepsw-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./psw-back-end/init.sql
        target: /tmp/explorerv-init.sql

  explorervStakeHolders:
    build:
      dockerfile: Dockerfile
      context: ./stakeholders-service/
      target: final
    restart: on-failure
    networks:
      - databasepswStakeHolders
    ports:
      - "44333:80"
    environment:
      DATABASE_HOST: databasepswStakeHolders
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorervStakeHolders
    depends_on:
      - databasepswStakeHolders

  databasepswStakeHolders:
    image: postgres:13
    restart: always
    networks:
      - databasepswStakeHolders
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: explorervStakeHolders
    ports:
      - "5432:5432"
    volumes:       
      - type: volume
        source: databasepswStakeHolders-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./stakeholders-service/init.sql
        target: /tmp/explorervStakeHolders-init.sql
    
    

volumes:
  database-data:
    name: server-database
  dataenk-data:
    name: server-dataenk
  databasepsw-data:
    name: explorerv
  databasepswStakeHolders-data:
    name: explorervStakeHolders
  databasef-data:
    name: server-databasefollower
  mongo_store:
  mongo_express_data:
  

networks:
  tourserver:
    name: tourserver
    driver: bridge
  encounterserver:
    name: encounterserver
    driver: bridge
  explorerv:
    name: explorerv
    driver: bridge
  explorervStakeHolders:
    name: explorervStakeHolders
    driver: bridge
  followerserver:
    name: followerserver
    driver: bridge
    
